Repository spring-cloud/spring-cloud-commons, pull requests merged in 2019-12, with the labels that each got.

#646 Making the Load Balancer and Circuit Breaker sections consistent
  docs/src/main/asciidoc/spring-cloud-circuitbreaker.adoc
  docs/src/main/asciidoc/spring-cloud-commons.adoc
Labels: documentation

#650 Make LoadBalancer cache conditional on no Ribbon default.
  spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/reactive/LoadBalancerBeanPostProcessorAutoConfiguration.java
  spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/reactive/OnNoRibbonDefaultCondition.java
  spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/reactive/ReactorLoadBalancerClientAutoConfiguration.java
  spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/config/BlockingLoadBalancerClientAutoConfiguration.java
  spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/config/LoadBalancerCacheAutoConfiguration.java
Labels: enhancement

#652 Add each PropertySource from PropertySourceLocators individually
  spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/config/PropertySourceBootstrapConfiguration.java
  spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/config/PropertySourceLocator.java
  spring-cloud-context/src/test/java/org/springframework/cloud/bootstrap/config/BootstrapConfigurationTests.java
  spring-cloud-context/src/test/java/org/springframework/cloud/context/refresh/ContextRefresherTests.java
  spring-cloud-context/src/test/resources/bootstrap.properties
Labels: in progress

#658 Zoned ServiceInstanceListSupplier
  docs/src/main/asciidoc/spring-cloud-commons.adoc
  spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/core/ZonePreferenceServiceInstanceListSupplier.java
  spring-cloud-loadbalancer/src/test/java/org/springframework/cloud/loadbalancer/core/ZonePreferenceServiceInstanceListSupplierTests.java
Labels: enhancement

#662 Use configuration properties instead of environment.
  docs/src/main/asciidoc/_configprops.adoc
  docs/src/main/asciidoc/spring-cloud-commons.adoc
  spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/reactive/LoadBalancerProperties.java
  spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/annotation/LoadBalancerClientConfiguration.java
  spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/core/ZonePreferenceServiceInstanceListSupplier.java
  spring-cloud-loadbalancer/src/test/java/org/springframework/cloud/loadbalancer/core/ZonePreferenceServiceInstanceListSupplierTests.java
Labels: enhancement
