Repository spring-cloud/spring-cloud-commons, pull requests merged in 2019-02, with the labels that each got.

#473 Fix override behaviour when using CompositePropertySource.
  spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/encrypt/EnvironmentDecryptApplicationInitializer.java
  spring-cloud-context/src/test/java/org/springframework/cloud/bootstrap/encrypt/EnvironmentDecryptApplicationInitializerTests.java
Labels: waiting-for-triage

#480 Ignores MapPropertySources not created by boot
  spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/BootstrapApplicationListener.java
  spring-cloud-context/src/test/java/org/springframework/cloud/bootstrap/BootstrapEnvironmentPostProcessorIntegrationTests.java
  spring-cloud-context/src/test/java/org/springframework/cloud/context/properties/ConfigurationPropertiesRebinderIntegrationTests.java
  spring-cloud-context/src/test/resources/META-INF/spring.factories
Labels: in progress

#482 Add ConditionalOnDiscoveryEnabled.
  README.adoc
  spring-cloud-commons/src/main/java/org/springframework/cloud/client/CommonsClientAutoConfiguration.java
  spring-cloud-commons/src/main/java/org/springframework/cloud/client/ConditionalOnDiscoveryEnabled.java
  spring-cloud-commons/src/test/java/org/springframework/cloud/client/CommonsClientAutoConfigurationTests.java
Labels: in progress

#486 Add new type property to KeyStore properties
  spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/encrypt/KeyProperties.java
Labels: enhancement, in progress
