Repository spring-cloud/spring-cloud-commons, pull requests merged in 2019-01, with the labels that each got.

#462 Only attempt to decrypt properties that are not overridden
  spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/encrypt/EnvironmentDecryptApplicationInitializer.java
  spring-cloud-context/src/test/java/org/springframework/cloud/bootstrap/encrypt/EnvironmentDecryptApplicationInitializerTests.java
Labels: enhancement

#469 Trim profile names in array
  spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/config/PropertySourceBootstrapConfiguration.java
Labels: bug, in progress

#474 Update to RELEASE version of dependency
  spring-cloud-loadbalancer/pom.xml
Labels: bug
