Repository spring-cloud/spring-cloud-commons, pull requests merged in 2020-01, with the labels that each got.

#626 Add once method for Customizer of circuit breaker
  docs/src/main/asciidoc/spring-cloud-circuitbreaker.adoc
  spring-cloud-commons/src/main/java/org/springframework/cloud/client/circuitbreaker/Customizer.java
  spring-cloud-commons/src/test/java/org/springframework/cloud/client/circuitbreaker/CustomizerTests.java
Labels: enhancement, in progress

#670 Adjusts ordering when override system properties is false.
  spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/config/PropertySourceBootstrapConfiguration.java
  spring-cloud-context/src/test/java/org/springframework/cloud/bootstrap/BootstrapOrderingCustomOverrideSystemPropertiesIntegrationTests.java
  spring-cloud-context/src/test/resources/ordering.properties
Labels: in progress

#679 Make LoadBalancerClientFactory bean conditional on missing bean.
  spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/config/LoadBalancerAutoConfiguration.java
Labels: waiting-for-triage

#468 Introduce property spring.cloud.bootstrap.additional-location according to spring.config.additional-location (#466)
  docs/src/main/asciidoc/spring-cloud-commons.adoc
  spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/BootstrapApplicationListener.java
  spring-cloud-context/src/test/java/org/springframework/cloud/bootstrap/config/BootstrapConfigurationTests.java
  spring-cloud-context/src/test/resources/bootstrap.properties
  spring-cloud-context/src/test/resources/external-properties/bootstrap.properties
Labels: in progress

#649 fix double checked locking with volatile
  spring-cloud-context/src/main/java/org/springframework/cloud/context/scope/GenericScope.java
Labels: in progress
