Repository spring-cloud/spring-cloud-commons, pull requests merged in 2020-03, with the labels that each got.

#705 Updates ContextRefresher to maintain property source ordering.
  spring-cloud-context/src/main/java/org/springframework/cloud/context/refresh/ContextRefresher.java
  spring-cloud-context/src/test/java/org/springframework/cloud/AdhocTestSuite.java
  spring-cloud-context/src/test/java/org/springframework/cloud/context/refresh/ContextRefresherOrderingIntegrationTests.java
Labels: in progress

#708 Typo correction in document
  docs/src/main/asciidoc/spring-cloud-circuitbreaker.adoc
Labels: documentation

#701 fix Endpoint ID 'service-registry' contains invalid characters, please migrate to a valid format
  spring-cloud-commons/src/main/java/org/springframework/cloud/client/serviceregistry/endpoint/ServiceRegistryEndpoint.java
  spring-cloud-commons/src/test/java/org/springframework/cloud/client/serviceregistry/endpoint/ServiceRegistryEndpointTests.java
Labels: in progress

#719 Add a property source that produces a random value that is cached
  docs/src/main/asciidoc/spring-cloud-commons.adoc
  spring-cloud-context/src/main/java/org/springframework/cloud/util/random/CachedRandomPropertySource.java
  spring-cloud-context/src/main/java/org/springframework/cloud/util/random/CachedRandomPropertySourceAutoConfiguration.java
  spring-cloud-context/src/main/resources/META-INF/spring.factories
  spring-cloud-context/src/test/java/org/springframework/cloud/context/refresh/ContextRefresherIntegrationTests.java
  spring-cloud-context/src/test/java/org/springframework/cloud/util/random/CachedRandomPropertySourceTests.java
  spring-cloud-context/src/test/resources/META-INF/spring.factories
  spring-cloud-context/src/test/resources/application.properties
Labels: enhancement
