Repository spring-cloud/spring-cloud-commons, pull requests merged in 2021-06, with the labels that each got.

#965 rewrite annotation on ReactiveRetryConfiguration
  spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/annotation/LoadBalancerClientConfiguration.java
Labels: bug

#969 Run all EnvironmentPostProcessors on refresh.
  spring-cloud-context/src/main/java/org/springframework/cloud/context/refresh/ConfigDataContextRefresher.java
  spring-cloud-context/src/test/java/org/springframework/cloud/bootstrap/encrypt/EncryptionIntegrationTests.java
  spring-cloud-context/src/test/java/org/springframework/cloud/context/refresh/ConfigDataContextRefresherIntegrationTests.java
  spring-cloud-context/src/test/java/org/springframework/cloud/context/test/TestConfigDataLoader.java
  spring-cloud-context/src/test/java/org/springframework/cloud/context/test/TestConfigDataLocationResolver.java
  spring-cloud-context/src/test/java/org/springframework/cloud/context/test/TestConfigDataResource.java
  spring-cloud-context/src/test/java/org/springframework/cloud/context/test/TestEnvPostProcessor.java
  spring-cloud-context/src/test/resources/META-INF/spring.factories
  spring-cloud-context/src/test/resources/application.properties
Labels: in progress

#974 Add a TaskSchedulerWrapper for downstream projects to use
  spring-cloud-commons/src/main/java/org/springframework/cloud/commons/util/TaskSchedulerWrapper.java
Labels: enhancement
