Repository spring-cloud/spring-cloud-commons, pull requests merged in 2021-07, with the labels that each got.

#970 Fixing spring.cloud.loadbalancer.repeat-health-check boolean
  docs/src/main/asciidoc/spring-cloud-commons.adoc
Labels: documentation

#975 Upgrade JUnit version (#973)
  spring-cloud-context-integration-tests/pom.xml
  spring-cloud-context-integration-tests/src/test/java/org/springframework/cloud/context/integration/JdbcConfigurationTests.java
  spring-cloud-context-integration-tests/src/test/java/org/springframework/cloud/context/integration/RefreshScopeIntegrationTests.java
Labels: in progress

#979 Polish `@RequestMapping` annotations
  spring-cloud-commons/src/test/java/org/springframework/cloud/client/loadbalancer/reactive/ReactorLoadBalancerExchangeFilterFunctionTests.java
  spring-cloud-context/src/test/java/org/springframework/cloud/context/scope/refresh/RefreshEndpointIntegrationTests.java
  spring-cloud-context/src/test/java/org/springframework/cloud/context/scope/refresh/RefreshScopeConfigurationTests.java
  spring-cloud-context/src/test/java/org/springframework/cloud/context/scope/refresh/RefreshScopeWebIntegrationTests.java
Labels: task

#985 Fix typo
  docs/src/main/asciidoc/spring-cloud-circuitbreaker.adoc
Labels: waiting-for-triage

#991 Added load-balancer cashe configuration warnings #775
  docs/src/main/asciidoc/spring-cloud-commons.adoc
Labels: waiting-for-triage

#989 Add `with()` method to support external ServiceInstanceListSupplier(#988)
  spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/core/ServiceInstanceListSupplierBuilder.java
Labels: enhancement
