Repository spring-cloud/spring-cloud-commons, pull requests merged in 2022-09, with the labels that each got.

#1146 Adapt to API change in Spring Framework
  spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/aot/LoadBalancerChildContextInitializer.java
Labels: task

#1147 Document lb aot support
  docs/src/main/asciidoc/spring-cloud-commons.adoc
Labels: documentation

#1151 Add @AliasFor declaration for @RefreshScope
  spring-cloud-context/src/main/java/org/springframework/cloud/context/config/annotation/RefreshScope.java
Labels: enhancement
