Repository spring-cloud/spring-cloud-commons, pull requests merged in 2022-11, with the labels that each got.

#1165 Lazy fills service instances to reduce max latency
  spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/core/LazyWeightedServiceInstanceList.java
  spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/core/WeightedServiceInstanceListSupplier.java
  spring-cloud-loadbalancer/src/test/java/org/springframework/cloud/loadbalancer/core/LazyWeightedServiceInstanceListTest.java
Labels: enhancement

#1167 Add note about removing configuration values and performing refreshes
  docs/src/main/asciidoc/spring-cloud-commons.adoc
Labels: waiting-for-triage

#1168 Allow overriding getScheme on DefaultServiceInstance.
  spring-cloud-commons/src/main/java/org/springframework/cloud/client/DefaultServiceInstance.java
  spring-cloud-commons/src/main/java/org/springframework/cloud/client/discovery/simple/SimpleDiscoveryProperties.java
  spring-cloud-commons/src/test/java/org/springframework/cloud/client/discovery/simple/SimpleDiscoveryClientPropertiesMappingTests.java
  spring-cloud-commons/src/test/java/org/springframework/cloud/client/discovery/simple/SimpleDiscoveryClientTests.java
  spring-cloud-loadbalancer/src/test/java/org/springframework/cloud/loadbalancer/core/HealthCheckServiceInstanceListSupplierTests.java
Labels: enhancement

#1175 Adds a check for Sleuth with 2022 cloud
  spring-cloud-commons/src/main/java/org/springframework/cloud/configuration/CompatibilityVerifierAutoConfiguration.java
  spring-cloud-commons/src/main/java/org/springframework/cloud/configuration/SleuthPresentVerifier.java
  spring-cloud-commons/src/test/java/org/springframework/cloud/configuration/SleuthPresentVerifierTests.java
Labels: enhancement

#1176 Lazily initialize child contexts with AOT initializers.
  spring-cloud-context/src/main/java/org/springframework/cloud/context/named/NamedContextFactory.java
  spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/aot/LoadBalancerChildContextInitializer.java
  spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/support/LoadBalancerClientFactory.java
  spring-cloud-loadbalancer/src/test/java/org/springframework/cloud/loadbalancer/aot/LoadBalancerChildContextInitializerTests.java
Labels: task
