Repository spring-cloud/spring-cloud-commons, pull requests merged in 2022-04, with the labels that each got.

#1096 Fix typo in spring-cloud-commons.adoc
  docs/src/main/asciidoc/spring-cloud-commons.adoc
Labels: documentation

#1098 Inject the class loader from the parent context into the child context
  spring-cloud-context/src/main/java/org/springframework/cloud/context/named/NamedContextFactory.java
  spring-cloud-context/src/test/java/org/springframework/cloud/context/named/NamedContextFactoryTests.java
Labels: bug

#1100 Request data context in blocking lb client
  spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/AsyncLoadBalancerInterceptor.java
  spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/AsyncLoadBalancerRequest.java
  spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/BlockingLoadBalancerRequest.java
  spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/HttpRequestLoadBalancerRequest.java
  spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/LoadBalancerRequestFactory.java
  spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/blocking/client/BlockingLoadBalancerClient.java
Labels: enhancement
