Repository spring-cloud/spring-cloud-commons, pull requests merged in 2022-10, with the labels that each got.

#1140 feat: expand the list by weights to implement weighted load balancing
  docs/src/main/asciidoc/spring-cloud-commons.adoc
  spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/core/ServiceInstanceListSupplierBuilder.java
  spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/core/WeightFunction.java
  spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/core/WeightedServiceInstanceListSupplier.java
  spring-cloud-loadbalancer/src/test/java/org/springframework/cloud/loadbalancer/core/ServiceInstanceListSupplierBuilderTests.java
  spring-cloud-loadbalancer/src/test/java/org/springframework/cloud/loadbalancer/core/WeightedServiceInstanceListSupplierTests.java
Labels: enhancement

#1152 Do not move position when there is only 1 instance
  spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/core/RoundRobinLoadBalancer.java
  spring-cloud-loadbalancer/src/test/java/org/springframework/cloud/loadbalancer/core/RoundRobinLoadBalancerTests.java
Labels: bug

#1155 Switch default in id from 0 to 8080 if server.port is not set
  spring-cloud-commons/src/main/java/org/springframework/cloud/commons/util/IdUtils.java
  spring-cloud-commons/src/test/java/org/springframework/cloud/commons/util/IdUtilsTests.java
Labels: in progress

#1159 Sets parentObservation on circuitbreaker Observation
  spring-cloud-commons/src/main/java/org/springframework/cloud/client/circuitbreaker/observation/CircuitBreakerObservationDocumentation.java
  spring-cloud-commons/src/main/java/org/springframework/cloud/client/circuitbreaker/observation/ObservedFunction.java
  spring-cloud-commons/src/main/java/org/springframework/cloud/client/circuitbreaker/observation/ObservedSupplier.java
  spring-cloud-commons/src/test/java/org/springframework/cloud/client/circuitbreaker/observation/ObservedCircuitBreakerTests.java
Labels: bug

#1160 Destroy and initialize beans within the correct context
  spring-cloud-context/src/main/java/org/springframework/cloud/context/properties/ConfigurationPropertiesRebinder.java
  spring-cloud-context/src/test/java/org/springframework/cloud/context/properties/ConfigurationPropertiesRebinderIntegrationTests.java
Labels: bug

#1163 feat: support autoconfigure WeightedServiceInstanceListSupplier
  docs/src/main/asciidoc/spring-cloud-commons.adoc
  spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/annotation/LoadBalancerClientConfiguration.java
  spring-cloud-loadbalancer/src/test/java/org/springframework/cloud/loadbalancer/annotation/LoadBalancerClientConfigurationTests.java
Labels: enhancement
