Repository spring-cloud/spring-cloud-commons, pull requests merged in 2023-01, with the labels that each got.

#1194 Add native hints for Caffeine cache.
  docs/src/main/asciidoc/spring-cloud-commons.adoc
  spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/config/LoadBalancerCacheAutoConfiguration.java
  spring-cloud-loadbalancer/src/main/resources/META-INF/spring/aot.factories
  spring-cloud-loadbalancer/src/test/java/org/springframework/cloud/loadbalancer/config/LoadBalancerCacheAutoConfigurationTests.java
Labels: waiting-for-triage

#1089 Provide setter for DefaultServiceInstance.secure
  spring-cloud-commons/src/main/java/org/springframework/cloud/client/DefaultServiceInstance.java
Labels: enhancement

#1197 Recheck for null service instance to avoid micrometer NPE.
  docs/src/main/asciidoc/_configprops.adoc
  spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/blocking/client/BlockingLoadBalancerClient.java
  spring-cloud-loadbalancer/src/main/resources/META-INF/additional-spring-configuration-metadata.json
Labels: bug

#1181 Removed ModifiedClasspathRunner and used the ClasspathExtensions from the Spring boot test support
  spring-cloud-commons/pom.xml
  spring-cloud-commons/src/test/java/org/springframework/cloud/client/discovery/ManagementServerPortUtilsTests.java
  spring-cloud-commons/src/test/java/org/springframework/cloud/client/loadbalancer/AbstractLoadBalancerAutoConfigurationTests.java
  spring-cloud-commons/src/test/java/org/springframework/cloud/client/loadbalancer/LoadBalancerAutoConfigurationTests.java
  spring-cloud-commons/src/test/java/org/springframework/cloud/client/serviceregistry/ServiceRegistryAutoConfigurationTests.java
  spring-cloud-context/pom.xml
  spring-cloud-context/src/test/java/org/springframework/cloud/autoconfigure/RefreshAutoConfigurationClassPathTests.java
  spring-cloud-context/src/test/java/org/springframework/cloud/autoconfigure/RefreshAutoConfigurationMoreClassPathTests.java
  spring-cloud-context/src/test/java/org/springframework/cloud/bootstrap/encrypt/RsaDisabledTests.java
  spring-cloud-loadbalancer/pom.xml
  spring-cloud-loadbalancer/src/test/java/org/springframework/cloud/loadbalancer/security/OAuth2LoadBalancerClientAutoConfigurationTests.java
  spring-cloud-starter-bootstrap/pom.xml
  spring-cloud-test-support/pom.xml
  spring-cloud-test-support/src/main/java/org/springframework/cloud/test/ClassPathExclusions.java
  spring-cloud-test-support/src/main/java/org/springframework/cloud/test/ClassPathOverrides.java
  spring-cloud-test-support/src/main/java/org/springframework/cloud/test/ModifiedClassPathClassLoader.java
  spring-cloud-test-support/src/main/java/org/springframework/cloud/test/ModifiedClassPathExtension.java
  spring-cloud-test-support/src/main/java/org/springframework/cloud/test/ModifiedClassPathRunner.java
  spring-cloud-test-support/src/test/java/org/springframework/cloud/test/ModifiedClassPathRunnerExclusionsTests.java
  spring-cloud-test-support/src/test/java/org/springframework/cloud/test/ModifiedClassPathRunnerOverridesTests.java
Labels: task
