Repository spring-cloud/spring-cloud-commons, pull requests merged in 2025-09, with the labels that each got.

#1579 Adapt to upstream Spring Boot changes
  spring-cloud-commons/src/main/java/org/springframework/cloud/client/HostInfoEnvironmentPostProcessor.java
  spring-cloud-commons/src/main/java/org/springframework/cloud/commons/ConfigDataMissingEnvironmentPostProcessor.java
  spring-cloud-commons/src/main/resources/META-INF/spring.factories
  spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/BootstrapConfigFileApplicationListener.java
  spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/RefreshBootstrapRegistryInitializer.java
  spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/TextEncryptorConfigBootstrapper.java
  spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/encrypt/DecryptEnvironmentPostProcessor.java
  spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/encrypt/TextEncryptorUtils.java
  spring-cloud-context/src/main/java/org/springframework/cloud/context/refresh/ConfigDataContextRefresher.java
  spring-cloud-context/src/main/java/org/springframework/cloud/util/random/CachedRandomPropertySourceEnvironmentPostProcessor.java
  spring-cloud-context/src/main/resources/META-INF/spring.factories
  spring-cloud-context/src/test/java/org/springframework/cloud/context/refresh/ConfigDataContextRefresherIntegrationTests.java
  spring-cloud-context/src/test/java/org/springframework/cloud/context/test/TestConfigDataLocationResolver.java
  spring-cloud-context/src/test/java/org/springframework/cloud/context/test/TestEnvPostProcessor.java
  spring-cloud-context/src/test/resources/META-INF/spring.factories
Labels: task

#1468 Make InstanceRegisteredEvent implements ResolvableTypeProvider
  spring-cloud-commons/src/main/java/org/springframework/cloud/client/discovery/event/InstanceRegisteredEvent.java
  spring-cloud-commons/src/test/java/org/springframework/cloud/client/serviceregistry/AbstractAutoServiceRegistrationTests.java
Labels: for-major-release

#1581 1580: Fixes property substitution problem for active profiles
  spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/config/PropertySourceBootstrapConfiguration.java
  spring-cloud-context/src/test/java/org/springframework/cloud/bootstrap/config/BootstrapConfigurationTests.java
Labels: waiting for feedback
