Repository spring-cloud/spring-cloud-commons, pull requests merged in 2025-01, with the labels that each got.

#1444 Fix typo
  spring-cloud-context/src/main/java/org/springframework/cloud/util/PropertyUtils.java
Labels: task

#1452 Use `Objects.equals()` instead
  spring-cloud-context/src/main/java/org/springframework/cloud/context/refresh/ContextRefresher.java
Labels: task

#1443 Polish RefreshAutoConfiguration to reuse constants
  spring-cloud-context/src/main/java/org/springframework/cloud/autoconfigure/RefreshAutoConfiguration.java
Labels: task

#1449 Revise dependencies
  spring-cloud-test-support/pom.xml
Labels: dependencies

#1445 Remove workaround for data source cycle
  spring-cloud-context/src/main/java/org/springframework/cloud/autoconfigure/RefreshAutoConfiguration.java
Labels: bug

#1454 Handle null in LoadBalancer Request and Response
  spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/stats/LoadBalancerTags.java
  spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/stats/MicrometerStatsLoadBalancerLifecycle.java
  spring-cloud-loadbalancer/src/test/java/org/springframework/cloud/loadbalancer/stats/MicrometerStatsLoadBalancerLifecycleTests.java
Labels: bug

#1456 Deprecate unused EnvironmentUtils
  spring-cloud-context/src/main/java/org/springframework/cloud/env/EnvironmentUtils.java
Labels: task

#1450 Move field ContextRefresher.REFRESH_ARGS_PROPERTY_SOURCE down to LegacyContextRefresher
  spring-cloud-context/src/main/java/org/springframework/cloud/context/refresh/ConfigDataContextRefresher.java
  spring-cloud-context/src/main/java/org/springframework/cloud/context/refresh/ContextRefresher.java
  spring-cloud-context/src/main/java/org/springframework/cloud/context/refresh/LegacyContextRefresher.java
Labels: waiting for feedback

#1457 Support configuring bean names as well as bean types for extra-refreshable and never-refreshable
  docs/modules/ROOT/partials/_configprops.adoc
  spring-cloud-context/src/main/java/org/springframework/cloud/autoconfigure/RefreshAutoConfiguration.java
  spring-cloud-context/src/main/java/org/springframework/cloud/context/properties/ConfigurationPropertiesRebinder.java
  spring-cloud-context/src/main/resources/META-INF/additional-spring-configuration-metadata.json
  spring-cloud-context/src/test/java/org/springframework/cloud/autoconfigure/RefreshAutoConfigurationTests.java
Labels: task
